/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package datastructures.queue;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

}
